version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements_dev.txt" }}-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements_dev.txt
      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "requirements_dev.txt" }}-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . .venv/bin/activate
            pytest
            pylint -j0 conf_as_code
            black --check --diff conf_as_code
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results
